import { useState } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useAcademicYear } from '@/hooks/useAcademicYear';
import {
  useMonthlyRevenue,
  useFeeSourceAnalysis,
  useCollectionPerformance,
  useOutstandingFees,
  useExpensePattern,
} from '@/hooks/queries/useAdminFinance';
import { useDailyFinanceSummary } from '@/hooks/queries/useExpenses';
import { Loader2, FileText, Printer, TrendingUp, PieChart, Users, AlertTriangle, BarChart3 } from 'lucide-react';
import { format } from 'date-fns';

const FEE_TYPE_LABELS: Record<string, string> = {
  monthly: 'মাসিক ফি', admission: 'ভর্তি ফি', session: 'সেশন চার্জ', exam: 'পরীক্ষা ফি', product_sales: 'পণ্য বিক্রয়', other: 'অন্যান্য',
};

const CATEGORY_LABELS: Record<string, string> = {
  salary: 'বেতন', utilities: 'ইউটিলিটি', maintenance: 'মেরামত', supplies: 'সরবরাহ', transport: 'পরিবহন', food: 'খাবার', other: 'অন্যান্য',
};

function PrintHeader({ title, dateRange }: { title: string; dateRange?: string }) {
  return (
    <div className="print-only mb-6 text-center">
      <h2 className="text-xl font-bold">{title}</h2>
      {dateRange && <p className="text-sm">{dateRange}</p>}
      <p className="text-xs text-muted-foreground mt-1">Generated: {format(new Date(), 'dd MMM yyyy, hh:mm a')} | Generated by Amar Hajira Smart</p>
      <hr className="mt-3 border-foreground/30" />
    </div>
  );
}

function DailySummaryReport() {
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const { data: summary, isLoading } = useDailyFinanceSummary(date);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between flex-wrap gap-3">
          <CardTitle className="font-bengali flex items-center gap-2">
            <FileText className="w-5 h-5" /> দৈনিক সারাংশ রিপোর্ট
          </CardTitle>
          <div className="flex items-center gap-3 no-print">
            <Input type="date" value={date} onChange={e => setDate(e.target.value)} className="w-auto" />
            <Button variant="outline" size="sm" onClick={() => window.print()}>
              <Printer className="w-4 h-4 mr-2" /> প্রিন্ট
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <PrintHeader title="দৈনিক আর্থিক সারাংশ" dateRange={format(new Date(date), 'dd MMMM yyyy')} />
        {isLoading ? (
          <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin" /></div>
        ) : (
          <div className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="p-4 border rounded-lg text-center">
                <p className="text-sm text-muted-foreground font-bengali">মোট আদায়</p>
                <p className="text-2xl font-bold text-emerald-600">৳{summary?.total_collection?.toLocaleString() || 0}</p>
                <p className="text-xs text-muted-foreground">{summary?.transaction_count || 0} টি ট্রানজেকশন</p>
              </div>
              <div className="p-4 border rounded-lg text-center">
                <p className="text-sm text-muted-foreground font-bengali">মোট খরচ</p>
                <p className="text-2xl font-bold text-red-600">৳{summary?.total_expenses?.toLocaleString() || 0}</p>
                <p className="text-xs text-muted-foreground">{summary?.expense_count || 0} টি এন্ট্রি</p>
              </div>
              <div className="p-4 border rounded-lg text-center">
                <p className="text-sm text-muted-foreground font-bengali">নেট ব্যালেন্স</p>
                <p className={`text-2xl font-bold ${(summary?.net_balance || 0) < 0 ? 'text-red-600' : 'text-blue-600'}`}>
                  ৳{summary?.net_balance?.toLocaleString() || 0}
                </p>
              </div>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function MonthlyRevenueReport() {
  const { activeYear } = useAcademicYear();
  const { data, isLoading } = useMonthlyRevenue(activeYear?.id);

  const totalIncome = data?.reduce((s, m) => s + m.income, 0) || 0;
  const totalExpense = data?.reduce((s, m) => s + m.expense, 0) || 0;

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between flex-wrap gap-3">
          <CardTitle className="font-bengali flex items-center gap-2">
            <TrendingUp className="w-5 h-5" /> মাসিক রেভিনিউ রিপোর্ট
          </CardTitle>
          <Button variant="outline" size="sm" onClick={() => window.print()} className="no-print">
            <Printer className="w-4 h-4 mr-2" /> প্রিন্ট
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <PrintHeader title="মাসিক রেভিনিউ রিপোর্ট" dateRange={`শিক্ষাবর্ষ: ${activeYear?.name || ''}`} />
        {isLoading ? (
          <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin" /></div>
        ) : !data?.length ? (
          <p className="text-center py-8 text-muted-foreground font-bengali">কোনো ডাটা পাওয়া যায়নি</p>
        ) : (
          <>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="font-bengali">মাস</TableHead>
                  <TableHead className="text-right font-bengali">আদায়</TableHead>
                  <TableHead className="text-right font-bengali">খরচ</TableHead>
                  <TableHead className="text-right font-bengali">নেট</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {data.map(m => (
                  <TableRow key={m.month}>
                    <TableCell className="font-medium">{m.month}</TableCell>
                    <TableCell className="text-right text-emerald-600 font-semibold">৳{m.income.toLocaleString()}</TableCell>
                    <TableCell className="text-right text-red-600 font-semibold">৳{m.expense.toLocaleString()}</TableCell>
                    <TableCell className={`text-right font-bold ${m.net < 0 ? 'text-red-600' : ''}`}>৳{m.net.toLocaleString()}</TableCell>
                  </TableRow>
                ))}
                <TableRow className="border-t-2 font-bold">
                  <TableCell className="font-bengali">মোট</TableCell>
                  <TableCell className="text-right text-emerald-600">৳{totalIncome.toLocaleString()}</TableCell>
                  <TableCell className="text-right text-red-600">৳{totalExpense.toLocaleString()}</TableCell>
                  <TableCell className={`text-right ${totalIncome - totalExpense < 0 ? 'text-red-600' : ''}`}>৳{(totalIncome - totalExpense).toLocaleString()}</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </>
        )}
      </CardContent>
    </Card>
  );
}

function FeeSourceReport() {
  const { activeYear } = useAcademicYear();
  const { data, isLoading } = useFeeSourceAnalysis(activeYear?.id);
  const total = data?.reduce((s, d) => s + d.amount, 0) || 0;

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between flex-wrap gap-3">
          <CardTitle className="font-bengali flex items-center gap-2">
            <PieChart className="w-5 h-5" /> ফি সোর্স বিশ্লেষণ
          </CardTitle>
          <Button variant="outline" size="sm" onClick={() => window.print()} className="no-print">
            <Printer className="w-4 h-4 mr-2" /> প্রিন্ট
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <PrintHeader title="ফি সোর্স বিশ্লেষণ রিপোর্ট" dateRange={`শিক্ষাবর্ষ: ${activeYear?.name || ''}`} />
        {isLoading ? (
          <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin" /></div>
        ) : (
          <>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="font-bengali">সোর্স</TableHead>
                  <TableHead className="text-right font-bengali">পরিমাণ</TableHead>
                  <TableHead className="text-right font-bengali">শতাংশ</TableHead>
                  <TableHead className="font-bengali">অনুপাত</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {data?.map(d => (
                  <TableRow key={d.source}>
                    <TableCell className="font-medium font-bengali">{FEE_TYPE_LABELS[d.source] || d.source}</TableCell>
                    <TableCell className="text-right font-semibold">৳{d.amount.toLocaleString()}</TableCell>
                    <TableCell className="text-right">{d.percentage}%</TableCell>
                    <TableCell>
                      <div className="w-full bg-muted rounded-full h-2">
                        <div className="bg-primary h-2 rounded-full" style={{ width: `${d.percentage}%` }} />
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
                <TableRow className="border-t-2 font-bold">
                  <TableCell className="font-bengali">মোট</TableCell>
                  <TableCell className="text-right">৳{total.toLocaleString()}</TableCell>
                  <TableCell className="text-right">100%</TableCell>
                  <TableCell />
                </TableRow>
              </TableBody>
            </Table>
          </>
        )}
      </CardContent>
    </Card>
  );
}

function CollectionPerformanceReport() {
  const { activeYear } = useAcademicYear();
  const { data, isLoading } = useCollectionPerformance(activeYear?.id);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between flex-wrap gap-3">
          <CardTitle className="font-bengali flex items-center gap-2">
            <Users className="w-5 h-5" /> কালেকশন পারফরম্যান্স
          </CardTitle>
          <Button variant="outline" size="sm" onClick={() => window.print()} className="no-print">
            <Printer className="w-4 h-4 mr-2" /> প্রিন্ট
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <PrintHeader title="কালেকশন পারফরম্যান্স রিপোর্ট" dateRange={`শিক্ষাবর্ষ: ${activeYear?.name || ''}`} />
        {isLoading ? (
          <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin" /></div>
        ) : !data?.length ? (
          <p className="text-center py-8 text-muted-foreground font-bengali">কোনো ডাটা পাওয়া যায়নি</p>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="font-bengali">অপারেটর</TableHead>
                <TableHead className="text-right font-bengali">মোট আদায়</TableHead>
                <TableHead className="text-right font-bengali">ট্রানজেকশন</TableHead>
                <TableHead className="text-right font-bengali">গড় আদায়</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {data.map(d => (
                <TableRow key={d.operator_id}>
                  <TableCell className="font-medium">{d.operator_name}</TableCell>
                  <TableCell className="text-right font-semibold">৳{d.total_amount.toLocaleString()}</TableCell>
                  <TableCell className="text-right">{d.transaction_count}</TableCell>
                  <TableCell className="text-right">৳{d.average.toLocaleString()}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </CardContent>
    </Card>
  );
}

function OutstandingReport() {
  const { activeYear } = useAcademicYear();
  const { data, isLoading } = useOutstandingFees(activeYear?.id);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between flex-wrap gap-3">
          <CardTitle className="font-bengali flex items-center gap-2">
            <AlertTriangle className="w-5 h-5" /> বকেয়া ফি ঝুঁকি রিপোর্ট
          </CardTitle>
          <Button variant="outline" size="sm" onClick={() => window.print()} className="no-print">
            <Printer className="w-4 h-4 mr-2" /> প্রিন্ট
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <PrintHeader title="বকেয়া ফি ঝুঁকি রিপোর্ট" dateRange={`শিক্ষাবর্ষ: ${activeYear?.name || ''}`} />
        {isLoading ? (
          <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin" /></div>
        ) : (
          <div className="space-y-6">
            {/* Summary */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 border rounded-lg text-center">
                <p className="text-sm text-muted-foreground font-bengali">মোট বকেয়া</p>
                <p className="text-2xl font-bold text-red-600">৳{data?.totalDue?.toLocaleString() || 0}</p>
              </div>
              <div className="p-4 border rounded-lg text-center">
                <p className="text-sm text-muted-foreground font-bengali">মোট বকেয়া রেকর্ড</p>
                <p className="text-2xl font-bold">{data?.totalRecords || 0}</p>
              </div>
            </div>

            {/* Class-wise */}
            <div>
              <h3 className="font-semibold mb-3 font-bengali">শ্রেণী ভিত্তিক বকেয়া</h3>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="font-bengali">শ্রেণী</TableHead>
                    <TableHead className="text-right font-bengali">বকেয়া পরিমাণ</TableHead>
                    <TableHead className="text-right font-bengali">রেকর্ড সংখ্যা</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data?.classDues?.map(c => (
                    <TableRow key={c.name}>
                      <TableCell className="font-medium">{c.name}</TableCell>
                      <TableCell className="text-right font-semibold text-red-600">৳{c.total.toLocaleString()}</TableCell>
                      <TableCell className="text-right">{c.count}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>

            {/* Top Defaulters */}
            {data?.topDefaulters && data.topDefaulters.length > 0 && (
              <div>
                <h3 className="font-semibold mb-3 font-bengali">🔴 বারবার বকেয়াদার (৩+ মাস)</h3>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="font-bengali">শিক্ষার্থী</TableHead>
                      <TableHead className="font-bengali">শ্রেণী</TableHead>
                      <TableHead className="text-right font-bengali">বকেয়া মাস</TableHead>
                      <TableHead className="text-right font-bengali">মোট বকেয়া</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {data.topDefaulters.map((d, i) => (
                      <TableRow key={i}>
                        <TableCell className="font-medium">{d.name}</TableCell>
                        <TableCell>{d.className}</TableCell>
                        <TableCell className="text-right">
                          <Badge variant="destructive">{d.unpaidMonths}</Badge>
                        </TableCell>
                        <TableCell className="text-right font-semibold text-red-600">৳{d.totalDue.toLocaleString()}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function ExpensePatternReport() {
  const { data, isLoading } = useExpensePattern(30);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between flex-wrap gap-3">
          <CardTitle className="font-bengali flex items-center gap-2">
            <BarChart3 className="w-5 h-5" /> খরচ প্যাটার্ন রিপোর্ট
          </CardTitle>
          <Button variant="outline" size="sm" onClick={() => window.print()} className="no-print">
            <Printer className="w-4 h-4 mr-2" /> প্রিন্ট
          </Button>
        </div>
        <CardDescription className="font-bengali">গত ৩০ দিনের খরচ বিশ্লেষণ</CardDescription>
      </CardHeader>
      <CardContent>
        <PrintHeader title="খরচ প্যাটার্ন রিপোর্ট" dateRange="গত ৩০ দিন" />
        {isLoading ? (
          <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin" /></div>
        ) : (
          <div className="space-y-6">
            {/* Average */}
            <div className="p-4 border rounded-lg text-center">
              <p className="text-sm text-muted-foreground font-bengali">দৈনিক গড় খরচ</p>
              <p className="text-2xl font-bold">৳{data?.avgDaily?.toLocaleString() || 0}</p>
            </div>

            {/* Category breakdown */}
            <div>
              <h3 className="font-semibold mb-3 font-bengali">ক্যাটাগরি ভিত্তিক খরচ</h3>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="font-bengali">ক্যাটাগরি</TableHead>
                    <TableHead className="text-right font-bengali">পরিমাণ</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data?.categoryTotals?.map(c => (
                    <TableRow key={c.category}>
                      <TableCell className="font-medium font-bengali">{CATEGORY_LABELS[c.category] || c.category}</TableCell>
                      <TableCell className="text-right font-semibold">৳{c.amount.toLocaleString()}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>

            {/* Spikes */}
            {data?.spikes && data.spikes.length > 0 && (
              <div>
                <h3 className="font-semibold mb-3 font-bengali">⚠️ অস্বাভাবিক খরচ (গড়ের ২x+)</h3>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead className="font-bengali">তারিখ</TableHead>
                      <TableHead className="text-right font-bengali">পরিমাণ</TableHead>
                      <TableHead className="text-right font-bengali">গড়ের তুলনায়</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {data.spikes.map(s => (
                      <TableRow key={s.date}>
                        <TableCell>{format(new Date(s.date), 'dd MMM yyyy')}</TableCell>
                        <TableCell className="text-right font-semibold text-red-600">৳{s.amount.toLocaleString()}</TableCell>
                        <TableCell className="text-right">
                          <Badge variant="destructive">{s.ratio}x</Badge>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}

            {/* Daily trend */}
            <div>
              <h3 className="font-semibold mb-3 font-bengali">দৈনিক খরচ ট্রেন্ড</h3>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="font-bengali">তারিখ</TableHead>
                    <TableHead className="text-right font-bengali">পরিমাণ</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {data?.dailyTrend?.slice(-15).map(d => (
                    <TableRow key={d.date}>
                      <TableCell>{format(new Date(d.date), 'dd MMM yyyy')}</TableCell>
                      <TableCell className="text-right font-semibold">৳{d.amount.toLocaleString()}</TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

export default function AdminFinanceReports() {
  return (
    <MainLayout title="Finance Reports" titleBn="ফাইন্যান্স রিপোর্ট">
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <FileText className="w-7 h-7 text-primary" />
            <span className="font-bengali">ফাইন্যান্স রিপোর্ট সমূহ</span>
          </h1>
          <p className="text-muted-foreground font-bengali">সুপার এডমিন — সব ধরনের আর্থিক রিপোর্ট এখানে</p>
        </div>

        <Tabs defaultValue="daily" className="w-full">
          <TabsList className="flex flex-wrap h-auto gap-1 no-print">
            <TabsTrigger value="daily" className="font-bengali">দৈনিক সারাংশ</TabsTrigger>
            <TabsTrigger value="monthly" className="font-bengali">মাসিক রেভিনিউ</TabsTrigger>
            <TabsTrigger value="source" className="font-bengali">ফি সোর্স</TabsTrigger>
            <TabsTrigger value="performance" className="font-bengali">পারফরম্যান্স</TabsTrigger>
            <TabsTrigger value="outstanding" className="font-bengali">বকেয়া ঝুঁকি</TabsTrigger>
            <TabsTrigger value="expense" className="font-bengali">খরচ প্যাটার্ন</TabsTrigger>
          </TabsList>

          <TabsContent value="daily"><DailySummaryReport /></TabsContent>
          <TabsContent value="monthly"><MonthlyRevenueReport /></TabsContent>
          <TabsContent value="source"><FeeSourceReport /></TabsContent>
          <TabsContent value="performance"><CollectionPerformanceReport /></TabsContent>
          <TabsContent value="outstanding"><OutstandingReport /></TabsContent>
          <TabsContent value="expense"><ExpensePatternReport /></TabsContent>
        </Tabs>
      </div>
    </MainLayout>
  );
}
